- name: move files
  hosts: all
  user: ubuntu
  tasks:
    - name: "copy files"
      become: yes
      copy: 
        src: ../../../../dist.tar.gz
        dest: /tmp/
    - name: Unarchive a file that is already on the remote machine
      unarchive:
        src: /tmp/dist.tar.gz
        dest: /tmp/
        remote_src: yes
    - name: "Set enviroment variables"
      shell: |
         export ENVIRONMENT=production
         export TYPEORM_CONNECTION=postgres
         export TYPEORM_ENTITIES=./src/modules/domain/**/*.entity.ts
         export TYPEORM_HOST=postgres.c5elejvwhxgd.us-west-2.rds.amazonaws.com
         export TYPEORM_PORT=5432
         export TYPEORM_USERNAME=postgres
         export TYPEORM_PASSWORD=udacity1234
         export TYPEORM_DATABASE=postgres

    - name: "Confirm enviroment"
      shell: |
         echo TYPEORM_HOST=$TYPEORM_HOST
         echo TYPEORM_PORT=$TYPEORM_PORT
         echo TYPEORM_USERNAME=$TYPEORM_USERNAME
         echo TYPEORM_PASSWORD=$TYPEORM_PASSWORD
         echo TYPEORM_DATABASE=$TYPEORM_DATABASE

    - name: "run server"
      shell: |
         cd /tmp/backend && sudo pm2 start npm -- run "start"